### ISSUE TITLE
При batch-запросе не сохраняется агрегатор, если после него обновляется детейл

### ISSUE THREAD

**Issue by StenvL** [Flexberry/NewPlatform.Flexberry.ORM.ODataService#100]
### Описание ошибки
При отправке batch-запроса если сначала обновляется агрегатор, а потом детейл, то изменённый агрегатор "перетирается" неизменённым при приходе детейла на редаетирование (можно отловить [тут](https://github.com/Flexberry/NewPlatform.Flexberry.ORM.ODataService/blob/28cc6ee12c609cdb680e0766ebea80c1d19078ad/NewPlatform.Flexberry.ORM.ODataService/Controllers/DataObjectController.ModifyData.cs#L472), когда приходит на обновление детейл: в объекте Request.Properties[DataObjectODataBatchHandler.DataObjectsToUpdatePropertyKey] агрегатор становится UnAltered и все изменения пропадают).

### Ожидаемое поведение
Изменения агрегатора не должны теряться.

### Шаги воспроизведения
1. Создать batch-запрос, в котором сначала обновляется агрегатор, затем - детейл.
2. Изменения в агрегаторе теряются.

**Comment by bratchikov** [comment]
Для начала нужно разработать тест, который повторит проблему. [Пример теста на batch](https://github.com/Flexberry/NewPlatform.Flexberry.ORM.ODataService/blob/1f7ddbad5a8a779830d109ae5848d5eb1a42fd01/Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/CRUD/Update/BusinessServersTest.cs#L147)
Есть предположение, что проблема связана с вычислимыми полями без DataServiceExpression в агрегаторе. Тест сначала пишем в простом варианте.
