### ISSUE TITLE
Проблемы при чтении объекта по ключу

### ISSUE THREAD

**Issue by KollegOFF** [Flexberry/NewPlatform.Flexberry.ORM.ODataService#16]
### Описание ошибки
В ответе сервиса, свойства мастера возвращаются как `null`, при запросе объекта по первичному ключу.

### Ожидаемое поведение
Если в запросе не указана опция $select, должен возвращаться объект со всеми собственными свойствами, иначе, только перечисленными в опции.
Если в запросе указана опция $expand, возвращаемый объект должен включать ссылочные свойства объекта, указанные в опции. Свойство указанное в опции $expand, может содержать вложенную опцию $select, с теми же правилами.
Примеры:
* [без опций](https://services.odata.org/V4/TripPinService/People('russellwhyte'))
* [$select](https://services.odata.org/V4/TripPinService/People('russellwhyte')?$select=UserName,FirstName,LastName,Gender)
* [$expand](https://services.odata.org/V4/TripPinService/People('russellwhyte')?$expand=Photo,Friends($select=FirstName,LastName,Gender))
* [$select & $expand](https://services.odata.org/V4/TripPinService/People('russellwhyte')?$select=UserName,FirstName,LastName,Gender&$expand=Photo,Friends($select=FirstName,LastName,Gender))

### Шаги воспроизведения
Для воспроизведения можно использовать текущую версию пакета.

### Пути решения
Проблема заключается в том, что метод обрабатывающий запрос на чтение объекта по первичному ключу, при получении объекта из сервиса данных, использует представление по умолчанию для типа этого объекта. Нужно использовать динамическое представление, создаваемое по запросу.

### Исходный код
* [`DataObjectController.GetGuid`](https://github.com/Flexberry/NewPlatform.Flexberry.ORM.ODataService/blob/082f89ab7a6cb9aa37628b87492278da38e2e563/NewPlatform.Flexberry.ORM.ODataService/Controllers/DataObjectController.cs#L188) - метод обрабатывающий запрос объекта по ключу.
* [`Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/CRUD/Read`](https://github.com/Flexberry/NewPlatform.Flexberry.ORM.ODataService/tree/develop/Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/CRUD/Read) - классы с тестами чтения объектов.

**Исходная ветка:** `develop`

### Тесты
Нужно добавить интеграционные тесты на чтение объекта по первичному ключу без опций и с опциями.

### Время
16 часов (4 часа - исправление, 12 часов - тесты).

**Comment by mao29** [comment]
Вроде эта ошибка поправлена ПР-ом https://github.com/Flexberry/NewPlatform.Flexberry.ORM.ODataService/pull/25
Можно закрывать наверное
