### ISSUE TITLE
Нельзя вернуть клиенту ошибку с кодом отличным от 500

### ISSUE THREAD

**Issue by emchigesheva** [Flexberry/NewPlatform.Flexberry.ORM.ODataService#18]
### Описание ошибки
HttpResponseException из OData-функции оборачивается в Internal Server Error.

### Ожидаемое поведение
Если в Odata-функции (или экшене) бросается HttpResponseException, содержащий HttpResponseMessage c ODataError и определенным кодом, клиенту должно возвращаться HttpResponseMessage.
Если в бросаемом HttpResponseException нет ODataError, исключение должно обрабатываться стандартно - 500-ой ошибкой.

### Шаги воспроизведения
1. Создать и зарегистрировать OData-функцию
2. Бросить внутри этой функции HttpResponseException с ODataError и HttpStatusCode, отличным от Internal Server Error
3. Послать запрос на выполнение функции
4. На клиент придет ошибка с 500 кодом

### Пути решения
Проблема заключается в том, что в контроллере все ошибки, возникающие при выполнении OData экшенов и функций, обрабатываются независимо от их типа и в каждом случае создается http-ответ с 500 кодом по умолчанию.
Необходимо добавить обработку для ошибок типа HttpResponseException, содержащих ODataError.

### Документация
- [HttpRequestMessageExtensions.CreateErrorResponse](https://docs.microsoft.com/en-us/previous-versions/aspnet/mt135696(v=vs.118))
- [ODataError](https://msdn.microsoft.com/en-us/library/microsoft.data.odata.odataerror(v=vs.113).aspx)
- [Пример вызова исключения в ODataController](https://stackoverflow.com/questions/19389070/error-handling-for-asp-net-odata-web-api)

### Исходный код
- [DataObjectController.PostODataActionsExecute](https://github.com/Flexberry/NewPlatform.Flexberry.ORM.ODataService/blob/530ea15a43e382a925caa5710bda9b95edc9841a/NewPlatform.Flexberry.ORM.ODataService/Controllers/DataObjectController.Actions.cs#L39) - метод, выполняющий OData экшн.
- [DataObjectController.GetODataFunctionsExecute](https://github.com/Flexberry/NewPlatform.Flexberry.ORM.ODataService/blob/530ea15a43e382a925caa5710bda9b95edc9841a/NewPlatform.Flexberry.ORM.ODataService/Controllers/DataObjectController.UserFunctions.cs#L39) - метод, выполняющий OData функцию.

**Ветка:** `<develop>`

### Тесты
Нужно добавить тесты на проверку проброса ошибки.

### Время
10 часов (2 часа - исправление, 8 часов - тесты)

**Comment by NicholasNoise** [comment]
А делегат DelegateAfterInternalServerError не помогает?

**Comment by mao29** [comment]
Наверное подходит, но зачем на прикладном уровне реализовывать логику, которая должна на уровне технологии быть? Если прикладной разработчик сгенерировал HttpResponseException, да еще и правильно сформировал содержимое ответа ОДата об ошибке, в соответствии со спецификацией, нужно чтобы технология не заставляла дополнительных телодвижений по корректной обработке таких ситуаций делать
