### ISSUE TITLE
Запрос без явного указания select'а с набором свойств обходит фильтрацию делегатом PropertyFilter и пытается вытянуть все свойства объекта.

### ISSUE THREAD

**Issue by DrKaotica** [Flexberry/NewPlatform.Flexberry.ORM.ODataService#205]
### Описание ошибки
*Запрос без явного указания select'а с набором свойств обходит фильтрацию делегатом PropertyFilter и пытается вытянуть все свойства объекта.*

### Ожидаемое поведение
*Ожидается, что фильтрация применится на такой запрос.*

**Comment by bratchikov** [comment]
Реализован тест для проверки данной ошибки в PR #211, но описываемое поведение не повторяется. Всё фильтруется как положено. Может быть есть какие-то неучтённые детали? @DrKaotica, помоги, пожалуйста, разобраться в чём проблема.
