### ISSUE TITLE
batchUpdate возвращает данные до обработки их в BusinessServer

### ISSUE THREAD

**Issue by PashaMasalkin** [Flexberry/NewPlatform.Flexberry.ORM.ODataService#36]
### Описание ошибки
batchUpdate возвращает данные не обработанные в BS

### Ожидаемое поведение
batchUpdate должен возвращать данные после обработки в BS

### Шаги воспроизведения
1. Запустить приложение и бэкенд из приложенных архивов.
2. Изменить на эдитформе поля Class1.per2 и calss2.per, сохранить.
3. Поле Class1.per1 не изменилось (не отработало его изменение в BS), после обновления страницы изменение отобразилось.

### Пути решения
Брать поля для возвращения resoponses из UpdateObject или Обновлять данные после batchUpdate

### Исходный код
**Проект на GitHub:** `https://github.com/Flexberry/NewPlatform.Flexberry.ORM.ODataService`
**Ветка:** `develop`

### Документация
Документации по batchUpdate нет, возможно стоит добавить?

### Скриншоты, полезные ссылки
[Product_59013.zip](https://github.com/Flexberry/NewPlatform.Flexberry.ORM.ODataService/files/3459733/Product_59013.zip)

РТЦ Тестирование и документирование\Примеры диаграмм для задач\Примеры ошибок в Caseberry\187885 Пример для проверки batchUpdate с обработкой в BS\
[187885 Пример для проверки batchUpdate с обработкой в BS.zip](https://github.com/Flexberry/NewPlatform.Flexberry.ORM.ODataService/files/3479790/187885.batchUpdate.BS.zip)

g=posts&m=18862#post18862

**Comment by bratchikov** [comment]
Решено добавлением поддержки select в конце batchUpdate.
